# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Control
set $mod1 Shift

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod


# kill focused window
bindsym $mod+Shift+q kill

# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop






# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle


# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"


# start a terminal
bindsym Return exec i3-sensible-terminal

# start dmenu (a program launcher)
bindsym d exec dmenu_run

# change focus
bindsym h focus left
bindsym j focus down
bindsym k focus up
bindsym l focus right

# enter fullscreen mode for the focused container
bindsym f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym st layout stacking
bindsym t layout tabbed
bindsym sl layout toggle split

# focus the parent container
bindsym a focus parent

mode "insert" {
 
        # back to normal: C-c or Escape
        bindsym $mod1+Escape mode "default"
        bindsym $mod1+c mode "default"
}

mode "split" {
        bindsym v split v mode "default"
        bindsym h split h mode "default"

        # back to normal: C-c or Escape
        bindsym $mod1+Escape mode "default"
        bindsym $mod1+c mode "default"
}

mode "layout" {
        bindsym s layout stacking mode "default"
        bindsym t layout tabbed mode "default"
        bindsym n layout toggle split mode "default"

        # move focused window
        bindsym h move left; mode "default"
        bindsym j move down; mode "default"
        bindsym k move up; mode "default"
        bindsym l move right; mode "default"

        # back to normal: C-c or Escape
        bindsym $mod1+Escape mode "default"
        bindsym $mod1+c mode "default"
}

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode
        bindsym s resize shrink width 10 px or 10 ppt
        bindsym b resize grow width 10 px or 10 ppt
        bindsym Shift+s resize shrink height 10 px or 10 ppt
        bindsym Shift+b resize grow height 10 px or 10 ppt

        # back to normal: C-c or Escape
        bindsym $mod1+Escape mode "default"
        bindsym $mod1+c mode "default"
}

bindsym i mode "insert"
bindsym s mode "split"
bindsym m mode "layout"
bindsym r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}
